<script>
  import { progress } from '../../lib/stores/progress.js';
  import { navigate } from '../../lib/router.js';
  import { calculateAllCertifications, getRecommendedNextActivity } from '../../lib/engines/coverage-calculator.js';
  import Card from '../../lib/components/Card.svelte';
  import Badge from '../../lib/components/Badge.svelte';
  import Button from '../../lib/components/Button.svelte';
  import RadarChart from '../../lib/components/RadarChart.svelte';

  import psm1 from '../../data/certifications/psm1.json';
  import pmiacp from '../../data/certifications/pmi-acp.json';
  import agilepm from '../../data/certifications/agilepmdm.json';
  import bcsba from '../../data/certifications/bcs-ba.json';
  import gds from '../../data/certifications/gds-standard.json';

  const certMaps = [psm1, pmiacp, agilepm, bcsba, gds];
  const certTabs = [
    { id: 'psm1', title: 'PSM I' },
    { id: 'pmi-acp', title: 'PMI-ACP' },
    { id: 'agilepmdm', title: 'AgilePM' },
    { id: 'bcs-ba', title: 'BCS BA' },
    { id: 'gds-standard', title: 'GDS Standard' }
  ];

  let activeTab = 'psm1';

  $: coverageResults = $progress ? calculateAllCertifications($progress, certMaps) : {};
  $: activeResult = coverageResults[activeTab] || null;
  $: activeCertMap = certMaps.find(c => c.id === activeTab) || null;
  $: recommendations = $progress ? getRecommendedNextActivity($progress, certMaps) : [];

  $: radarLabels = activeCertMap ? activeCertMap.domains.map(d => d.name) : [];
  $: radarDatasets = activeResult ? [{
    label: 'Coverage',
    data: activeResult.domains.map(d => d.percentage / 20),
    color: '#f0883e'
  }] : [];
  $: optimalDataset = activeResult ? [{
    label: 'Target (100%)',
    data: activeResult.domains.map(() => 5),
    color: '#30363d'
  }] : [];

  function getStatusBadge(pct) {
    if (pct >= 70) return { variant: 'success', text: 'On Track' };
    if (pct >= 40) return { variant: 'warning', text: 'Needs Work' };
    return { variant: 'danger', text: 'Not Started' };
  }

  function exportLearningEvidence() {
    const date = new Date().toLocaleDateString('en-GB', { day: 'numeric', month: 'long', year: 'numeric' });
    const p = $progress;
    let html = `<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><title>Learning Evidence Portfolio</title>
<style>
  @page { margin: 20mm; }
  body { font-family: 'IBM Plex Sans', sans-serif; background: #fff; color: #333; line-height: 1.5; max-width: 800px; margin: 0 auto; padding: 40px; }
  h1 { font-family: 'IBM Plex Mono', monospace; font-size: 24px; color: #1a1a1a; border-bottom: 3px solid #f0883e; padding-bottom: 8px; }
  h2 { font-family: 'IBM Plex Mono', monospace; font-size: 18px; color: #333; margin-top: 24px; }
  table { width: 100%; border-collapse: collapse; margin: 12px 0; }
  th, td { text-align: left; padding: 8px 12px; border-bottom: 1px solid #ddd; font-size: 13px; }
  th { background: #f5f5f5; font-weight: 600; }
  .meta { color: #666; font-size: 13px; margin: 8px 0; }
  .score { font-weight: 600; }
  .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #ddd; font-size: 12px; color: #999; }
</style></head><body>
<h1>Learning Evidence Portfolio</h1>
<p class="meta">Generated: ${date} &bull; AgileFocus Sandbox</p>

<h2>Completed Activities</h2>
<table><tr><th>Type</th><th>Count</th></tr>
<tr><td>Exercises</td><td>${(p.completed_exercises || []).length}</td></tr>
<tr><td>Simulations</td><td>${(p.completed_simulations || []).length}</td></tr>
<tr><td>Modules</td><td>${(p.completed_modules || []).length}</td></tr></table>

<h2>Certification Coverage</h2>
<table><tr><th>Certification</th><th>Coverage</th><th>Domains on Track</th></tr>`;

    for (const cert of certMaps) {
      const r = coverageResults[cert.id];
      if (r) {
        const onTrack = r.domains.filter(d => d.percentage >= 50).length;
        html += `<tr><td>${cert.title}</td><td class="score">${r.overall_percentage}%</td><td>${onTrack}/${r.total_domains}</td></tr>`;
      }
    }

    html += `</table>

<h2>Knowledge Check Scores</h2>
<table><tr><th>Quiz</th><th>Score</th></tr>`;
    for (const [key, score] of Object.entries(p.knowledge_check_scores || {})) {
      html += `<tr><td>${key.replace('quiz-', '').toUpperCase()}</td><td>${score}%</td></tr>`;
    }

    html += `</table>
<div class="footer">This document was generated by AgileFocus (https://opencode.ai) as portfolio evidence for certification applications. The data reflects completion of activities within the AgileFocus sandbox environment.</div>
</body></html>`;

    const blob = new Blob([html], { type: 'text/html' });
    const url = URL.createObjectURL(blob);
    const w = window.open('about:blank');
    if (w) {
      w.document.write(html);
      w.document.close();
      w.focus();
      w.print();
    } else {
      const a = document.createElement('a');
      a.href = url;
      a.download = 'agilefocus-evidence-portfolio.html';
      a.click();
    }
    URL.revokeObjectURL(url);
  }
</script>

<div class="cert-dash">
  <header class="cert-dash__header">
    <div>
      <h1>Certification Coverage</h1>
      <p class="cert-dash__subtitle">Last updated: {new Date().toLocaleDateString()}</p>
    </div>
    <Button variant="secondary" on:click={exportLearningEvidence}>Export Learning Evidence</Button>
  </header>

  <div class="cert-dash__tabs">
    {#each certTabs as tab (tab.id)}
      <button class="cert-dash__tab" class:cert-dash__tab--active={activeTab === tab.id} on:click={() => activeTab = tab.id}>
        {tab.title}
        {#if coverageResults[tab.id]}
          <span class="cert-dash__tab-pct">{coverageResults[tab.id].overall_percentage}%</span>
        {/if}
      </button>
    {/each}
  </div>

  {#if activeCertMap && activeResult}
    <div class="cert-dash__layout">
      <div class="cert-dash__main">
        <div class="cert-dash__overall">
          <div class="cert-dash__overall-ring">
            <svg viewBox="0 0 120 120" class="cert-dash__score-svg">
              <circle cx="60" cy="60" r="52" fill="none" stroke="var(--color-bg-primary)" stroke-width="8" />
              <circle cx="60" cy="60" r="52" fill="none" stroke="var(--color-accent-primary)" stroke-width="8"
                stroke-dasharray="326.7" stroke-dashoffset={326.7 - (326.7 * activeResult.overall_percentage / 100)}
                stroke-linecap="round" transform="rotate(-90 60 60)" />
              <text x="60" y="52" text-anchor="middle" dominant-baseline="central"
                font-size="28" font-weight="700" font-family="var(--font-display)" fill="var(--color-text-primary)">
                {activeResult.overall_percentage}%
              </text>
              <text x="60" y="76" text-anchor="middle" dominant-baseline="central"
                font-size="10" font-family="var(--font-display)" fill="var(--color-text-secondary)">
                Overall
              </text>
            </svg>
          </div>
          <div class="cert-dash__overall-info">
            <h2>{activeCertMap.title}</h2>
            <p class="cert-dash__source">{activeCertMap.source}</p>
            {#if activeResult.quiz_score !== undefined}
              <Badge variant="info" text="Quiz: {activeResult.quiz_score}%" />
            {/if}
            <Button variant="primary" size="sm" on:click={() => navigate('/learn/quiz/' + activeCertMap.id)}>Take Quiz</Button>
          </div>
        </div>

        {#if radarLabels.length > 0}
          <Card>
            <h3>Domain Coverage</h3>
            <RadarChart labels={radarLabels} datasets={[...radarDatasets, ...optimalDataset]} />
          </Card>
        {/if}

        <Card>
          <h3>Domain Breakdown</h3>
          <div class="cert-dash__table">
            <div class="cert-dash__table-header">
              <span>Domain</span>
              <span>Weight</span>
              <span>Coverage</span>
              <span>Activities</span>
              <span>Status</span>
            </div>
            {#each activeResult.domains as domain (domain.domain_id)}
              <div class="cert-dash__table-row">
                <span class="cert-dash__domain-name">{domain.name}</span>
                <span class="cert-dash__domain-weight">{domain.weight}%</span>
                <span class="cert-dash__domain-pct">{domain.percentage}%</span>
                <span class="cert-dash__domain-act">{domain.activities_completed}/{domain.activities_total}</span>
                <span>
                  <Badge variant={getStatusBadge(domain.percentage).variant} text={getStatusBadge(domain.percentage).text} />
                </span>
              </div>
            {/each}
          </div>
        </Card>

        {#if activeResult.domains.filter(d => d.percentage < 50).length > 0}
          <Card variant="warning">
            <h3>Gap Analysis</h3>
            <p class="cert-dash__gap-intro">The following domains need attention (below 50% coverage):</p>
            <div class="cert-dash__gaps">
              {#each activeResult.domains.filter(d => d.percentage < 50) as gap (gap.domain_id)}
                <div class="cert-dash__gap">
                  <strong>{gap.name}</strong> ({gap.percentage}%)
                  <p class="cert-dash__gap-suggest">
                    Complete: {gap.activities_matched.length > 0 ? gap.activities_matched.join(', ') : 'No activities yet'}
                  </p>
                </div>
              {/each}
            </div>
          </Card>
        {/if}

        {#if recommendations.length > 0}
          <Card>
            <h3>Highest Leverage Next Activity</h3>
            <div class="cert-dash__leverage">
              <strong>{recommendations[0].label.name}</strong>
              <p>Improves {recommendations[0].domains_improved} domain(s) across {recommendations[0].certifications.length} certification(s)</p>
              <Button variant="primary" size="sm" on:click={() => navigate(recommendations[0].label.link)}>Start</Button>
            </div>
          </Card>
        {/if}
      </div>

      <aside class="cert-dash__sidebar">
        <Card>
          <h3>Recommended Learning Path</h3>
          <div class="cert-dash__recs">
            {#if recommendations.length === 0}
              <p class="cert-dash__recs-empty">All activities complete!</p>
            {:else}
              {#each recommendations.slice(0, 5) as rec, i (rec.activity_id)}
                <div class="cert-dash__rec">
                  <span class="cert-dash__rec-num">{i + 1}</span>
                  <div class="cert-dash__rec-body">
                    <strong>{rec.label.name}</strong>
                    <div class="cert-dash__rec-meta">
                      <Badge variant="info" text={rec.label.type} />
                      <span class="cert-dash__rec-time">{rec.label.time}</span>
                    </div>
                    <p class="cert-dash__rec-doms">Covers {rec.domains_improved} domain(s)</p>
                    <Button variant="ghost" size="sm" on:click={() => navigate(rec.label.link)}>Start</Button>
                  </div>
                </div>
              {/each}
            {/if}
          </div>
        </Card>
      </aside>
    </div>
  {:else}
    <p class="cert-dash__empty">Select a certification to view coverage.</p>
  {/if}
</div>

<style>
  .cert-dash { display: flex; flex-direction: column; gap: var(--space-6); }
  .cert-dash__header { display: flex; align-items: flex-start; justify-content: space-between; gap: var(--space-4); }
  .cert-dash__subtitle { font-size: var(--text-sm); color: var(--color-text-secondary); margin-top: var(--space-1); }

  .cert-dash__tabs { display: flex; gap: var(--space-1); border-bottom: 1px solid var(--color-border); }
  .cert-dash__tab { padding: var(--space-2) var(--space-4); background: none; border: none; border-bottom: 2px solid transparent; color: var(--color-text-secondary); cursor: pointer; font-family: var(--font-display); font-size: var(--text-sm); display: flex; align-items: center; gap: var(--space-2); }
  .cert-dash__tab:hover { color: var(--color-text-primary); }
  .cert-dash__tab--active { color: var(--color-text-primary); border-bottom-color: var(--color-accent-primary); }
  .cert-dash__tab-pct { font-size: var(--text-xs); color: var(--color-accent-primary); }

  .cert-dash__layout { display: grid; grid-template-columns: 1fr 300px; gap: var(--space-4); }
  .cert-dash__main { display: flex; flex-direction: column; gap: var(--space-4); }

  .cert-dash__overall { display: flex; align-items: center; gap: var(--space-6); }
  .cert-dash__overall-ring { width: 120px; height: 120px; flex-shrink: 0; }
  .cert-dash__score-svg { width: 100%; height: 100%; }
  .cert-dash__overall-info h2 { font-size: var(--text-xl); }
  .cert-dash__source { font-size: var(--text-sm); color: var(--color-text-secondary); margin: var(--space-1) 0 var(--space-3); }

  .cert-dash__table { display: flex; flex-direction: column; margin-top: var(--space-3); }
  .cert-dash__table-header, .cert-dash__table-row { display: grid; grid-template-columns: 2fr 60px 80px 80px 100px; gap: var(--space-2); padding: var(--space-2) var(--space-3); align-items: center; font-size: var(--text-sm); }
  .cert-dash__table-header { background: var(--color-bg-primary); border-radius: var(--radius-sm); font-weight: 600; font-family: var(--font-display); font-size: var(--text-xs); text-transform: uppercase; letter-spacing: 0.03em; color: var(--color-text-secondary); }
  .cert-dash__table-row { border-bottom: 1px solid var(--color-border); }
  .cert-dash__domain-weight, .cert-dash__domain-pct { font-family: var(--font-display); font-weight: 600; }

  .cert-dash__gap-intro { font-size: var(--text-sm); margin: var(--space-2) 0; color: var(--color-text-secondary); }
  .cert-dash__gaps { display: flex; flex-direction: column; gap: var(--space-3); }
  .cert-dash__gap { font-size: var(--text-sm); }
  .cert-dash__gap-suggest { font-size: var(--text-xs); color: var(--color-text-secondary); margin-top: var(--space-1); }

  .cert-dash__leverage { display: flex; flex-direction: column; gap: var(--space-2); margin-top: var(--space-2); }
  .cert-dash__leverage p { font-size: var(--text-sm); color: var(--color-text-secondary); }

  .cert-dash__sidebar { display: flex; flex-direction: column; gap: var(--space-4); }

  .cert-dash__recs { display: flex; flex-direction: column; gap: var(--space-3); margin-top: var(--space-3); }
  .cert-dash__recs-empty { font-size: var(--text-sm); color: var(--color-text-success); text-align: center; padding: var(--space-4); }
  .cert-dash__rec { display: flex; gap: var(--space-3); align-items: flex-start; }
  .cert-dash__rec-num { font-family: var(--font-display); font-size: var(--text-sm); font-weight: 700; color: var(--color-accent-primary); width: 20px; flex-shrink: 0; }
  .cert-dash__rec-body { display: flex; flex-direction: column; gap: var(--space-1); }
  .cert-dash__rec-body strong { font-size: var(--text-sm); }
  .cert-dash__rec-meta { display: flex; align-items: center; gap: var(--space-2); font-size: var(--text-xs); }
  .cert-dash__rec-time { color: var(--color-text-secondary); }
  .cert-dash__rec-doms { font-size: var(--text-xs); color: var(--color-text-secondary); }
  .cert-dash__empty { text-align: center; padding: var(--space-8); color: var(--color-text-secondary); }
</style>
